### ISSUE TITLE
No module

### ISSUE THREAD

**Issue by blackhattokyo** [klezVirus/inceptor#13]
python3 inceptor.py -hh                                                                                      1 ⨯
Traceback (most recent call last):
  File "/home/kali/Desktop/av bypass/inceptor/inceptor/inceptor.py", line 12, in <module>
    from generators.PowerShellArtifactGenerator import PowerShellArtifactGenerator
  File "/home/kali/Desktop/av bypass/inceptor/inceptor/generators/PowerShellArtifactGenerator.py", line 9, in <module>
    from obfuscators.powershell.Karmaleon import Karmaleon
  File "/home/kali/Desktop/av bypass/inceptor/inceptor/obfuscators/powershell/Karmaleon.py", line 6, in <module>
    from obfuscators.powershell.chameleon.chameleon import Chameleon
ModuleNotFoundError: No module named 'obfuscators.powershell.chameleon.chameleon'

**Comment by bschroed96** [comment]
https://github.com/klezVirus/inceptor/issues/10
