### ISSUE TITLE
Definition file not working

### ISSUE THREAD

**Issue by klezVirus** [klezVirus/inceptor#26]
Hi, I tried your tool using a .def file created with 

```
dumpbin /exports file.dll /out:file.def
```

I provided the `file.def` as `--exports` parameter but I get the following error when executed: 
```
Traceback (most recent call last):
  File "inceptor.py", line 268, in <module>
    generator = NativeArtifactGenerator(binary_abs_path,
  File "C:\Users\Username\Documents\Tools\inceptor\inceptor\generators\NativeArtifactGenerator.py", line 147, in __init__
    self.dll_compiler_args["/DEF"] = f'"{os.path.abspath(self.exports)}"'
TypeError: 'NoneType' object does not support item assignment
```

How can I set custom exports?

_Originally posted by @CT-H00K in https://github.com/klezVirus/inceptor/issues/22#issuecomment-966664175_

**Comment by klezVirus** [comment]
Hi @CT-H00K, I've tried now using the dev branch and it seems the issue has been already fixed.

**Comment by CT-H00K** [comment]
Hi @klezVirus , I cannot test it since the dev branch is still kinda buggy and not properly executing. 
![inceptor_bug](https://user-images.githubusercontent.com/73144188/142158345-99590148-530d-42f1-9b7d-8474ecd58154.png)

I've tried with venv and pipenv for the virtual environment.

Do you plan switching to poetry in the future?
https://python-poetry.org/

**Comment by klezVirus** [comment]
Yeah you're right, I'm still solving a few issues before merging. I'll merge Dev and main very soon anyway.
Didn't know poetry, seems very useful, I'll consider that for sure, thanks for the suggestion! ;)

**Comment by Revozop** [comment]
how to import the .def file ? 

![image](https://user-images.githubusercontent.com/91875992/161344895-c6025c91-737e-4007-a382-3086acb43751.png)

**Comment by klezVirus** [comment]
Hi @Revozop, the definition file can be added with the `--exports` parameter   Let me know if it works, I'm working on a few updates at the moment and don't remember if this is working fine in the main branch.

You can find more examples in the wiki page [Example By Scenario](https://github.com/klezVirus/inceptor/wiki/Examples-by-scenario)
