### ISSUE TITLE
Bug Dinvoke Amsi

### ISSUE THREAD

**Issue by Mantraufo** [klezVirus/inceptor#7]
python inceptor.py dotnet -t donut client.exe -o kiwi.exe --sgn --sign --delay 120 -m dinvoke -m amsi

[*] Multiple compatible templates identified, choose one:
  0: bypass-dinvoke.cs
  1: bypass-dinvoke_manual_mapping.cs
  $> 0
Traceback (most recent call last):
  File "C:\Users\LENOVO\Documents\NoteMalware\inceptor\inceptor\engine\modules\AmsiModule.py", line 62, in __init__
    kwargs["template"] = self.generate(kwargs=kwargs)
  File "C:\Users\LENOVO\Documents\NoteMalware\inceptor\inceptor\engine\modules\AmsiModule.py", line 99, in generate
    template.process_modules()
  File "C:\Users\LENOVO\Documents\NoteMalware\inceptor\inceptor\engine\Template.py", line 76, in process_modules
    self.libraries += module.libraries
AttributeError: 'NoneType' object has no attribute 'libraries'
[-] Exception building AmsiModule

**Comment by klezVirus** [comment]
Hi Mantraufo, thanks for pointing that out, it was an issue with the architecture which is now required for Dinvoke. Fixed in [cf0f9fd](https://github.com/klezVirus/inceptor/commit/cf0f9fdf483913d17dacc401b34e81e8b3b67b7d).
